swagger: '2.0'
info:
  version: 0.7.5
  title: WeConnect API
host: 'localhost:7000'
basePath: /api/v1
paths:
  /businesses:
    get:
      summary: Gets all businesses.
      responses:
        '200':
          $ref: '#/responses/200'
        '400':
          $ref: '#/responses/400'
  /businesses/:
    post:
      summary: Creates a new business. 
      consumes:
        - application/json
      parameters:
        - in: body
          name: update business
          description: route to update a business
          schema:
            $ref: '#/definitions/business'
      responses:
        '200':
          $ref: '#/responses/200'
        '400':
          $ref: '#/responses/400'
  /businesses/{id}:
    put:
      summary: Update an existing business.
      consumes:
        - application/json
      parameters:
        - in: body
          name: update business
          description: route to update a business
          schema:
            type: string
        - in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          $ref: '#/responses/200'
        '400':
          $ref: '#/responses/400'
    delete:
      summary: Delete an existing business.
      consumes:
        - application/json
      parameters:
        - in: body
          name: delete business business
          description: route to update a business
          schema:
            type: string
        - in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          $ref: '#/responses/200'
        '400':
          $ref: '#/responses/400'
    get:
      summary: Retrieve a particular business.
      consumes:
        - application/json
      parameters:
        - in: body
          name: get a business
          description: route to get a business
          schema:
            type: string
        - in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          $ref: '#/responses/200'
        '400':
          $ref: '#/responses/400'

          
          
responses:
  '200':
    description: OK
    schema:
      type: object
  '400':
    description: Bad Request
    
    
definitions:
  business:
    type: string
    required:
      - business_name
    properties:
      id:
        type: integer
      business_name:
        type: string
      business_description:
        type: string
      business_location:
        type: string
      business_category:
        type: string
